"""Update relationship

Revision ID: 378d0338a6a1
Revises: 9e310ed3eb4e
Create Date: 2026-02-02 20:47:20.915992

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "378d0338a6a1"
down_revision: Union[str, Sequence[str], None] = "9e310ed3eb4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("is_completed", sa.Boolean(), nullable=False))
    op.drop_constraint(op.f("tasks_user_id_fkey"), "tasks", type_="foreignkey")
    op.create_foreign_key(None, "tasks", "users", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(op.f("tasks_user_id_fkey"), "tasks", "users", ["user_id"], ["id"])
    op.drop_column("tasks", "is_completed")
    # ### end Alembic commands ###
